---
deployment:
  tasks:
    - /bin/cp -R core /home7/ferre3151357/public_html/conecta/
    - /bin/cp -R assets /home7/ferre3151357/public_html/conecta/
    - /bin/cp -R templates /home7/ferre3151357/public_html/conecta/
    - /bin/cp -R auth /home7/ferre3151357/public_html/conecta/
    - /bin/cp -R modules /home7/ferre3151357/public_html/conecta/
    - /bin/cp -f .htaccess /home7/ferre3151357/public_html/conecta/
    - /bin/cp -f schema.sql /home7/ferre3151357/public_html/conecta/
