-- ================================================================
-- Ferreira & Sa — Mover pasta_apta para finalizado no Pipeline
-- Estrategia: usar nome do lead (mais confiavel que client_id)
-- 255 clientes identificados com processo ja distribuido
-- ================================================================

-- VERIFICAR ANTES:
SELECT COUNT(*) as total_a_mover FROM pipeline_leads
WHERE stage = 'pasta_apta'
  AND name IN (
  'Cezar Augusto Pereira de Carvalho',
  'Luiz Eduardo de Sá',
  'Anesio Francisco da Silva',
  'Douglas Silva de Souza x Defesa em Ação de Alimentos',
  'LEONARDO TAVARES FERREIRA',
  'ROSANGELA DOS SANTOS',
  'Kamilly Victoria Franco Duarte',
  'THAISSA ROCHA LIMA DE OLIVEIRA',
  'AILANDA ALINE LESSA FARIA',
  'Cleitom Avelino Eduardo',
  'Misã Guimarães Lopes',
  'Rayane Joyce da Silva Machado',
  'TAMIRES DA SILVA',
  'JOICE CORREA CEZARIO',
  'Maria Marinete Lins Silva',
  'Gilmar Ferreira Gomes',
  'Jéssica Ribeiro Honório',
  'Luiz Fernando de Souza Severino',
  'KAUAN RODRIGUES DE SOUZA',
  'Maria Aparecida de Lima Cassimiro',
  'Ana Paula Almeida Diniz x Danos Morais',
  'Paula Roberta Sodré de Almeida Querino',
  'Anderson Silva de Souza Candido',
  'TAMYRIS CARVALHO E CARVALHO',
  'Joseleia Moreira de Oliveira',
  'ALANE SANTOS OLIVEIRA',
  'José Rafael da Silva (inventário - Manoel Mariano da Silva) - indicação Vagner',
  'Joziane da Silveira Lino',
  'ANA CLAUDIA GUIMARÃES DA SILVA',
  'Claudinei',
  'SUELEN DE PAULA DA SILVA',
  'Thais Rodrigues da Silva',
  'LUCCA CELANO PEREIRA RIBEIRO',
  'Arnaldo x Pensão (réu)',
  'Leonardo da Silva Felipe',
  'LUCIANA DINIZ BARBOSA',
  'Marceli Santos Marins x Alimentos',
  'Rita Pires dos Santos',
  'Rachel Nardelli Rosa',
  'BEBIANA DE OLIVEIRA REIS',
  'SUELEN DA COSTA SILVA',
  'Patrick Gomes das Graças Passifico',
  'Ana Carolina Bragança Pinto x Alimentos',
  'Gilmara Gonçalves',
  'Fernanda x Divórcio',
  'TAINA CRISTINA DE LIMA DOS SANTOS',
  'ROBSON MACHADO SOARES',
  'MARIA ISABELA ELIOTERIO LIMA TINOCO',
  'Lorena Quintanilha Soares x Alimentos',
  'MONIQUE ALVES CARVALHO',
  'Natasha Carolina Pereira da Costa',
  'SEBASTIÃO DE OLIVEIRA',
  'Mariele de Souza Barbosa',
  'Jéssica da Silva',
  'Mélodi Batista Cruz',
  'Bianca Nascimento Conceição',
  'Angela de Oliveira Louzada Costa',
  'Enayle Garcia Fontes x Execução Cível',
  'AMANDA FERREIRA DE LIMA',
  'Juliana Matias Euclides',
  'DAYANA CABRAL FERNANDES',
  'Dayane de Araújo Amancio x Desconto em Folha',
  'SARAH CRISTINA DE SOUZA RIBEIRO,',
  'Eliene Lima dos Santos Almeida',
  'ESPÓLIO DE WALDIR ESTEVES GUIMARÃES',
  'Jorge Ferreira Gomes',
  'Juliana Alves Santana',
  'Ana Caroline Carvalho Neris Lourenço',
  'Peterson Pereira Mayworm',
  'Thiago Guimarães de Melo',
  'Maria Eduarda da Silva Sousa',
  'Thaissa Rocha Lima de Oliveira',
  'RAIANE MARTINS DAMASCENO',
  'AuraTijuca (mensalistA)',
  'JEOVANA MARCOLINO SOUZA DO CARMO',
  'Priscila Almeida Silva Anastácio x Alimentos',
  'MAIARA PEREIRA CARDOZO',
  'CRISTIANE ANICETO DA COSTA',
  'NATAN e NEUSA',
  'Vanessa de Souza',
  'Marcus Vinicius Gomes Boechat',
  'ALINE APARECIDA DE SOUZA VIEIRA MALAQUIAS',
  'EDILAINE FERREIRA ALVES',
  'CINTHIA MARA DA SILVA PINHEIRO GAMA',
  'Francisco Tomazi Manoel',
  'Vitória Aparecida da Silva',
  'Maria Girlandia Barbosa Gomes',
  'Sara Ramão da Silva',
  'Mariucha dos Santos Silva',
  'Carlos Augusto Ferreira Monteiro',
  'Fernanda x Guarda',
  'CASSIANE FARIA CONCEIÇÃO',
  'KAYLA KEROLAYNE BORGES DA SILVA',
  'Márcia Aparecida Costa da Silva',
  'Deise Cristina Ramos de Oliveira',
  'Allan Louzada x Execução (Juliana)',
  'JULIANA FERREIRA DE SOUZA BARBOSA',
  'Aldo de Souza Lourenço',
  'ANA PAULA ALMEIDA DINIZ',
  'Jessica Regina dos Santos Machado x GPX',
  'RAFAELLA DE LIMA BENEDITO',
  'LIDIANE MARIA DE SOUZA',
  'Diogo Nascimento de Oliveira',
  'MARIA CLARA MOREIRA DE LIMA',
  'Fernanda Ribeiro de Oliveira',
  'GILDSON SILVA DE FARIA',
  'Ruana Constantino Torres x Desconto em Folha',
  'Mariana Joana Pereira',
  'Thamires Calabar x Alimentos',
  'Diego de Souza Villarinho',
  'Mariella dos Santos Silva',
  'Carina Marcelino Correa',
  'GISELE SILVA MACHADO AMARO CARDOZO',
  'Lorena Quintanilha Soares',
  'CÉLIA FERREIRA DA SILVA',
  'AILA DOS SANTOS GAIA',
  'MAURÍCIO MAIA FERREIRA',
  'Caroline da Silva David',
  'Jéssica Gregório da Silva Abreu',
  'Alícia de Carvalho Wogel',
  'GISELI RODRIGUES CORREA',
  'Myllena x Leilão',
  'JÉSSICA MAIARA ROCHA DA COSTA',
  'Tamara Vitória de Souza Moreno',
  'Allan Louzada',
  'Kaylane Rangel da Silva',
  'Guilherme da Silva Benício',
  'Maria Clara Moreira de Lima',
  'Lohana da Silva Teixeira de Paula',
  'Gabriela Cardoso Lobato',
  'VALQUÍRIA DA SILVA VIERA',
  'LORENA QUINTANILHA SOARES',
  'GABRIELE RIBEIRO GOMES',
  'Gabriela Cristina de Oliveira Gonçalves',
  'Dayane de Araújo Amancio x Execução de Alimentos',
  'Claudinei Marcolino',
  'ALEXANDRO DA SILVA MARTINS',
  'Rayane rodrigues da Silva',
  'Fernanda x Pensão',
  'JENIFER DA SILVA BARBOSA',
  'Tiago x Execução (defesa)',
  'Igor Yahnn Neves de Carvalho x Divórcio Extra',
  'WEVERTON JAIRO ARTHUR DOS SANTOS',
  'STEPHANIA DOS SANTOS ROCHA',
  'Nilton dos Santos Silva',
  'Rayane Aparecida Pereira da Silva',
  'Nataly Cerqueira Mattos Silva',
  'Norma Monteiro Pereira Leite Machado',
  'Vanderleia Américo',
  'MAISA SILVA SANTOS',
  'KAMILA DA SILVA ELEOTÉRIO X Revisional',
  'Aghata Stefany Nascimento da Silva',
  'EMERSON ALVARENGA DE MACEDO',
  'PAOLA FERNANDA SILVA DE ASSIS x Alimentos',
  'MARCIA HONORATO NUNES MEDEIROS',
  'Dayana Cabral Fernandes',
  'Estoel Nathan Costa Silva',
  'Leonardo Ribeiro Braga',
  'Valquiria da Silva Vieira',
  'ESTER DOS SANTOS PATRICIO',
  'Ruana Constantino Torres x Execução de Alimentos',
  'VAGNER DE OLIVEIRA GAMA',
  'Silvia Neurauter x GPX',
  'Erika de Sena Antunes x Alimentos',
  'Queila Conceição dos Santos',
  'JOSELEIA MOREIRA DE OLIVEIRA',
  'Aline Fernandes Carvalho x Alimentos',
  'INDIANE CHRISTINE MORAIS DE SOUZA',
  'Rodrigo França Penha',
  'Jaqueline Oliveira Silva Santos',
  'KAREN LOPES DOS SANTOS',
  'Renan Nascimento dos Santos x GPX (Danos Materiais)',
  'Carolaine de Souza Barros',
  'Iara Dos Santos Gonçalves',
  'Solange Sacramento Guedes Ferreira',
  'Adriano Matheus Leoncio de Jesus x Execução de Alimentos - Rito de Prisão',
  'Adriano da Silva Gomes',
  'Yasmim Cruz da Silva',
  'AMANDA GOMES DE OLIVEIRA',
  'Lívia Silva Nunes Mendonça',
  'IVAN DE SOUZA MORAES',
  'Aline Aparecida da Silva',
  'Diana Alves Segales Ganduxe',
  'Ana Claudia Guimarães x Alimentos',
  'CONDOMÍNIO AURA TIJUCA',
  'LEONARDO RIBEIRO BRAGA',
  'IRLEI RIBEIRO SOUZA',
  'Aline Fernandes Carvalho x Indenização DP',
  'Rodrigo José do Nascimento Alves',
  'Ester Gonsalves Romão',
  'Raphael de Souza Silva',
  'Viviane Lyrio Barboza',
  'Josiana da Costa da Silva Correa',
  'CINEONE DA CONCEIÇÃO LIMA',
  'Wallace Gabriel Pereira Tamiozzo de Oliveira',
  'WILSON HELIO SILVA',
  'DEISE FERREIRA DO NASCIMENTO',
  'RAFAELLY SOUSA DA SILVA',
  'Joice Correa Cezario',
  'Cristina Mara Oliveira dos Santos x Alimentos',
  'Letícia Vitória dos Santos Avelino x GPX',
  'DÉBORA LOPES GONÇALVES',
  'EDUARDA HONORATO TOLEDO',
  'Thaís Beringhy dos Santos Barros',
  'Michele Ferreira da Conceição'
);

-- EXECUTAR (descomente para rodar):
/*
UPDATE pipeline_leads
SET
  stage = 'finalizado',
  converted_at = IFNULL(converted_at, NOW()),
  updated_at = NOW()
WHERE stage = 'pasta_apta'
  AND name IN (
  'Cezar Augusto Pereira de Carvalho',
  'Luiz Eduardo de Sá',
  'Anesio Francisco da Silva',
  'Douglas Silva de Souza x Defesa em Ação de Alimentos',
  'LEONARDO TAVARES FERREIRA',
  'ROSANGELA DOS SANTOS',
  'Kamilly Victoria Franco Duarte',
  'THAISSA ROCHA LIMA DE OLIVEIRA',
  'AILANDA ALINE LESSA FARIA',
  'Cleitom Avelino Eduardo',
  'Misã Guimarães Lopes',
  'Rayane Joyce da Silva Machado',
  'TAMIRES DA SILVA',
  'JOICE CORREA CEZARIO',
  'Maria Marinete Lins Silva',
  'Gilmar Ferreira Gomes',
  'Jéssica Ribeiro Honório',
  'Luiz Fernando de Souza Severino',
  'KAUAN RODRIGUES DE SOUZA',
  'Maria Aparecida de Lima Cassimiro',
  'Ana Paula Almeida Diniz x Danos Morais',
  'Paula Roberta Sodré de Almeida Querino',
  'Anderson Silva de Souza Candido',
  'TAMYRIS CARVALHO E CARVALHO',
  'Joseleia Moreira de Oliveira',
  'ALANE SANTOS OLIVEIRA',
  'José Rafael da Silva (inventário - Manoel Mariano da Silva) - indicação Vagner',
  'Joziane da Silveira Lino',
  'ANA CLAUDIA GUIMARÃES DA SILVA',
  'Claudinei',
  'SUELEN DE PAULA DA SILVA',
  'Thais Rodrigues da Silva',
  'LUCCA CELANO PEREIRA RIBEIRO',
  'Arnaldo x Pensão (réu)',
  'Leonardo da Silva Felipe',
  'LUCIANA DINIZ BARBOSA',
  'Marceli Santos Marins x Alimentos',
  'Rita Pires dos Santos',
  'Rachel Nardelli Rosa',
  'BEBIANA DE OLIVEIRA REIS',
  'SUELEN DA COSTA SILVA',
  'Patrick Gomes das Graças Passifico',
  'Ana Carolina Bragança Pinto x Alimentos',
  'Gilmara Gonçalves',
  'Fernanda x Divórcio',
  'TAINA CRISTINA DE LIMA DOS SANTOS',
  'ROBSON MACHADO SOARES',
  'MARIA ISABELA ELIOTERIO LIMA TINOCO',
  'Lorena Quintanilha Soares x Alimentos',
  'MONIQUE ALVES CARVALHO',
  'Natasha Carolina Pereira da Costa',
  'SEBASTIÃO DE OLIVEIRA',
  'Mariele de Souza Barbosa',
  'Jéssica da Silva',
  'Mélodi Batista Cruz',
  'Bianca Nascimento Conceição',
  'Angela de Oliveira Louzada Costa',
  'Enayle Garcia Fontes x Execução Cível',
  'AMANDA FERREIRA DE LIMA',
  'Juliana Matias Euclides',
  'DAYANA CABRAL FERNANDES',
  'Dayane de Araújo Amancio x Desconto em Folha',
  'SARAH CRISTINA DE SOUZA RIBEIRO,',
  'Eliene Lima dos Santos Almeida',
  'ESPÓLIO DE WALDIR ESTEVES GUIMARÃES',
  'Jorge Ferreira Gomes',
  'Juliana Alves Santana',
  'Ana Caroline Carvalho Neris Lourenço',
  'Peterson Pereira Mayworm',
  'Thiago Guimarães de Melo',
  'Maria Eduarda da Silva Sousa',
  'Thaissa Rocha Lima de Oliveira',
  'RAIANE MARTINS DAMASCENO',
  'AuraTijuca (mensalistA)',
  'JEOVANA MARCOLINO SOUZA DO CARMO',
  'Priscila Almeida Silva Anastácio x Alimentos',
  'MAIARA PEREIRA CARDOZO',
  'CRISTIANE ANICETO DA COSTA',
  'NATAN e NEUSA',
  'Vanessa de Souza',
  'Marcus Vinicius Gomes Boechat',
  'ALINE APARECIDA DE SOUZA VIEIRA MALAQUIAS',
  'EDILAINE FERREIRA ALVES',
  'CINTHIA MARA DA SILVA PINHEIRO GAMA',
  'Francisco Tomazi Manoel',
  'Vitória Aparecida da Silva',
  'Maria Girlandia Barbosa Gomes',
  'Sara Ramão da Silva',
  'Mariucha dos Santos Silva',
  'Carlos Augusto Ferreira Monteiro',
  'Fernanda x Guarda',
  'CASSIANE FARIA CONCEIÇÃO',
  'KAYLA KEROLAYNE BORGES DA SILVA',
  'Márcia Aparecida Costa da Silva',
  'Deise Cristina Ramos de Oliveira',
  'Allan Louzada x Execução (Juliana)',
  'JULIANA FERREIRA DE SOUZA BARBOSA',
  'Aldo de Souza Lourenço',
  'ANA PAULA ALMEIDA DINIZ',
  'Jessica Regina dos Santos Machado x GPX',
  'RAFAELLA DE LIMA BENEDITO',
  'LIDIANE MARIA DE SOUZA',
  'Diogo Nascimento de Oliveira',
  'MARIA CLARA MOREIRA DE LIMA',
  'Fernanda Ribeiro de Oliveira',
  'GILDSON SILVA DE FARIA',
  'Ruana Constantino Torres x Desconto em Folha',
  'Mariana Joana Pereira',
  'Thamires Calabar x Alimentos',
  'Diego de Souza Villarinho',
  'Mariella dos Santos Silva',
  'Carina Marcelino Correa',
  'GISELE SILVA MACHADO AMARO CARDOZO',
  'Lorena Quintanilha Soares',
  'CÉLIA FERREIRA DA SILVA',
  'AILA DOS SANTOS GAIA',
  'MAURÍCIO MAIA FERREIRA',
  'Caroline da Silva David',
  'Jéssica Gregório da Silva Abreu',
  'Alícia de Carvalho Wogel',
  'GISELI RODRIGUES CORREA',
  'Myllena x Leilão',
  'JÉSSICA MAIARA ROCHA DA COSTA',
  'Tamara Vitória de Souza Moreno',
  'Allan Louzada',
  'Kaylane Rangel da Silva',
  'Guilherme da Silva Benício',
  'Maria Clara Moreira de Lima',
  'Lohana da Silva Teixeira de Paula',
  'Gabriela Cardoso Lobato',
  'VALQUÍRIA DA SILVA VIERA',
  'LORENA QUINTANILHA SOARES',
  'GABRIELE RIBEIRO GOMES',
  'Gabriela Cristina de Oliveira Gonçalves',
  'Dayane de Araújo Amancio x Execução de Alimentos',
  'Claudinei Marcolino',
  'ALEXANDRO DA SILVA MARTINS',
  'Rayane rodrigues da Silva',
  'Fernanda x Pensão',
  'JENIFER DA SILVA BARBOSA',
  'Tiago x Execução (defesa)',
  'Igor Yahnn Neves de Carvalho x Divórcio Extra',
  'WEVERTON JAIRO ARTHUR DOS SANTOS',
  'STEPHANIA DOS SANTOS ROCHA',
  'Nilton dos Santos Silva',
  'Rayane Aparecida Pereira da Silva',
  'Nataly Cerqueira Mattos Silva',
  'Norma Monteiro Pereira Leite Machado',
  'Vanderleia Américo',
  'MAISA SILVA SANTOS',
  'KAMILA DA SILVA ELEOTÉRIO X Revisional',
  'Aghata Stefany Nascimento da Silva',
  'EMERSON ALVARENGA DE MACEDO',
  'PAOLA FERNANDA SILVA DE ASSIS x Alimentos',
  'MARCIA HONORATO NUNES MEDEIROS',
  'Dayana Cabral Fernandes',
  'Estoel Nathan Costa Silva',
  'Leonardo Ribeiro Braga',
  'Valquiria da Silva Vieira',
  'ESTER DOS SANTOS PATRICIO',
  'Ruana Constantino Torres x Execução de Alimentos',
  'VAGNER DE OLIVEIRA GAMA',
  'Silvia Neurauter x GPX',
  'Erika de Sena Antunes x Alimentos',
  'Queila Conceição dos Santos',
  'JOSELEIA MOREIRA DE OLIVEIRA',
  'Aline Fernandes Carvalho x Alimentos',
  'INDIANE CHRISTINE MORAIS DE SOUZA',
  'Rodrigo França Penha',
  'Jaqueline Oliveira Silva Santos',
  'KAREN LOPES DOS SANTOS',
  'Renan Nascimento dos Santos x GPX (Danos Materiais)',
  'Carolaine de Souza Barros',
  'Iara Dos Santos Gonçalves',
  'Solange Sacramento Guedes Ferreira',
  'Adriano Matheus Leoncio de Jesus x Execução de Alimentos - Rito de Prisão',
  'Adriano da Silva Gomes',
  'Yasmim Cruz da Silva',
  'AMANDA GOMES DE OLIVEIRA',
  'Lívia Silva Nunes Mendonça',
  'IVAN DE SOUZA MORAES',
  'Aline Aparecida da Silva',
  'Diana Alves Segales Ganduxe',
  'Ana Claudia Guimarães x Alimentos',
  'CONDOMÍNIO AURA TIJUCA',
  'LEONARDO RIBEIRO BRAGA',
  'IRLEI RIBEIRO SOUZA',
  'Aline Fernandes Carvalho x Indenização DP',
  'Rodrigo José do Nascimento Alves',
  'Ester Gonsalves Romão',
  'Raphael de Souza Silva',
  'Viviane Lyrio Barboza',
  'Josiana da Costa da Silva Correa',
  'CINEONE DA CONCEIÇÃO LIMA',
  'Wallace Gabriel Pereira Tamiozzo de Oliveira',
  'WILSON HELIO SILVA',
  'DEISE FERREIRA DO NASCIMENTO',
  'RAFAELLY SOUSA DA SILVA',
  'Joice Correa Cezario',
  'Cristina Mara Oliveira dos Santos x Alimentos',
  'Letícia Vitória dos Santos Avelino x GPX',
  'DÉBORA LOPES GONÇALVES',
  'EDUARDA HONORATO TOLEDO',
  'Thaís Beringhy dos Santos Barros',
  'Michele Ferreira da Conceição'
);

-- Verificacao final:
SELECT stage, COUNT(*) as qtd FROM pipeline_leads
GROUP BY stage ORDER BY qtd DESC;
*/

-- Esperado apos execucao:
-- finalizado: ~396+
-- pasta_apta: ~180 (ativos reais)