<?php
/**
 * Ferreira & Sá Hub — Correção de acentuação determinística
 *
 * Sem IA, sem custo: dicionário fechado de palavras jurídicas em PT-BR que
 * inequivocamente levam acento, aplicado com word boundary preservando case.
 *
 * Uso:
 *   require_once __DIR__ . '/core/functions_acentos.php';
 *   $textoCorrigido = corrigir_acentos_juridico($textoBruto);
 *
 * Princípios:
 * - SÓ inclui palavras que NÃO têm homônimo sem acento em PT-BR técnico/comum.
 *   Ex: 'nao' → 'não' sempre. 'sao' está fora porque pode ser "São Paulo" OU
 *   o verbo "são" — exigiria contexto, deixo passar.
 * - Nomes próprios incluídos só quando são extremamente comuns no judiciário
 *   (Sá, André, César, etc) e raramente aparecem em outra grafia.
 * - Preserva CASE original (Decisao → Decisão; DECISAO → DECISÃO).
 *
 * Amanda 11/06/2026.
 */

if (!function_exists('corrigir_acentos_juridico')) {

/**
 * Retorna o dicionário fechado, cacheado entre chamadas.
 * Estrutura: array<string sem acento minúsculo, string com acento>
 */
function _dic_acentos_juridico() {
    static $dic = null;
    if ($dic !== null) return $dic;
    $dic = array(
        // ── Termos jurídicos comuns ──
        'acao' => 'ação',
        'acoes' => 'ações',
        'acordao' => 'acórdão',
        'acordaos' => 'acórdãos',
        'admissao' => 'admissão',
        'alegacao' => 'alegação',
        'alegacoes' => 'alegações',
        'apreciacao' => 'apreciação',
        'apreensao' => 'apreensão',
        'apuracao' => 'apuração',
        'audiencia' => 'audiência',
        'audiencias' => 'audiências',
        'celeridade' => 'celeridade',
        'certidao' => 'certidão',
        'certidoes' => 'certidões',
        'cessao' => 'cessão',
        'ciencia' => 'ciência',
        'citacao' => 'citação',
        'citacoes' => 'citações',
        'cobranca' => 'cobrança',
        'cogitacao' => 'cogitação',
        'concessao' => 'concessão',
        'conciliacao' => 'conciliação',
        'condenacao' => 'condenação',
        'condicao' => 'condição',
        'conexao' => 'conexão',
        'confirmacao' => 'confirmação',
        'contestacao' => 'contestação',
        'contestacoes' => 'contestações',
        'contradicao' => 'contradição',
        'cumulacao' => 'cumulação',
        'declaracao' => 'declaração',
        'decisao' => 'decisão',
        'decisoes' => 'decisões',
        'defesa' => 'defesa',
        'demanda' => 'demanda',
        'denegacao' => 'denegação',
        'denuncia' => 'denúncia',
        'desconstituicao' => 'desconstituição',
        'designacao' => 'designação',
        'destituicao' => 'destituição',
        'devolucao' => 'devolução',
        'discussao' => 'discussão',
        'disposicao' => 'disposição',
        'distribuicao' => 'distribuição',
        'divisao' => 'divisão',
        'divorcio' => 'divórcio',
        'edicao' => 'edição',
        'efetivacao' => 'efetivação',
        'eleicao' => 'eleição',
        'eletronica' => 'eletrônica',
        'eletronico' => 'eletrônico',
        'embargos' => 'embargos',
        'especificacao' => 'especificação',
        'estavel' => 'estável',
        'exclusao' => 'exclusão',
        'execucao' => 'execução',
        'expedicao' => 'expedição',
        'extincao' => 'extinção',
        'familia' => 'família',
        'feria' => 'féria',
        'ficticia' => 'fictícia',
        'fixacao' => 'fixação',
        'forum' => 'fórum',
        'fundamentacao' => 'fundamentação',
        'gratuidade' => 'gratuidade',
        'habilitacao' => 'habilitação',
        'homologacao' => 'homologação',
        'identificacao' => 'identificação',
        'impugnacao' => 'impugnação',
        'inclusao' => 'inclusão',
        'indenizacao' => 'indenização',
        'indenizatoria' => 'indenizatória',
        'inicial' => 'inicial',
        'inscricao' => 'inscrição',
        'instrucao' => 'instrução',
        'intencao' => 'intenção',
        'interposicao' => 'interposição',
        'interpretacao' => 'interpretação',
        'intimacao' => 'intimação',
        'intimacoes' => 'intimações',
        'inversao' => 'inversão',
        'investigacao' => 'investigação',
        'invocacao' => 'invocação',
        'juiz' => 'juiz', // já acentuado, mantém
        'juiza' => 'juíza',
        'juntada' => 'juntada',
        'justica' => 'justiça',
        'litigancia' => 'litigância',
        'litigio' => 'litígio',
        'lugar' => 'lugar',
        'manifestacao' => 'manifestação',
        'manifestacoes' => 'manifestações',
        'medida' => 'medida',
        'mencao' => 'menção',
        'mensagem' => 'mensagem',
        'merito' => 'mérito',
        'ministerio' => 'ministério',
        'modificacao' => 'modificação',
        'morais' => 'morais',
        'movimentacao' => 'movimentação',
        'movimentacoes' => 'movimentações',
        'mudanca' => 'mudança',
        'nacao' => 'nação',
        'negacao' => 'negação',
        'nomeacao' => 'nomeação',
        'notificacao' => 'notificação',
        'novacao' => 'novação',
        'nulidade' => 'nulidade',
        'objecao' => 'objeção',
        'objecoes' => 'objeções',
        'obrigacao' => 'obrigação',
        'observacao' => 'observação',
        'observacoes' => 'observações',
        'ocorrencia' => 'ocorrência',
        'oficio' => 'ofício',
        'oitiva' => 'oitiva',
        'omissao' => 'omissão',
        'opiniao' => 'opinião',
        'opcao' => 'opção',
        'oposicao' => 'oposição',
        'orgao' => 'órgão',
        'orgaos' => 'órgãos',
        'orientacao' => 'orientação',
        'orientacoes' => 'orientações',
        'origem' => 'origem',
        'originaria' => 'originária',
        'originario' => 'originário',
        'originarios' => 'originários',
        'pagina' => 'página',
        'paginas' => 'páginas',
        'parcial' => 'parcial',
        'paragrafo' => 'parágrafo',
        'paraibuna' => 'Paraíbuna',
        'particao' => 'partição',
        'parto' => 'parto',
        'passivel' => 'passível',
        'penalidade' => 'penalidade',
        'pendencia' => 'pendência',
        'percepcao' => 'percepção',
        'pericia' => 'perícia',
        'pessoa' => 'pessoa',
        'peticao' => 'petição',
        'peticoes' => 'petições',
        'porem' => 'porém',
        'posicao' => 'posição',
        'possibilidade' => 'possibilidade',
        'pratica' => 'prática',
        'praticas' => 'práticas',
        'preclusao' => 'preclusão',
        'predio' => 'prédio',
        'prejulgamento' => 'prejulgamento',
        'preliminar' => 'preliminar',
        'preocupacao' => 'preocupação',
        'preparacao' => 'preparação',
        'presuncao' => 'presunção',
        'principal' => 'principal',
        'pre-processual' => 'pré-processual',
        'previa' => 'prévia',
        'previo' => 'prévio',
        'previsao' => 'previsão',
        'pricipio' => 'princípio',
        'principio' => 'princípio',
        'principios' => 'princípios',
        'prisao' => 'prisão',
        'procedencia' => 'procedência',
        'procuracao' => 'procuração',
        'procuracoes' => 'procurações',
        'producao' => 'produção',
        'profissional' => 'profissional',
        'progressao' => 'progressão',
        'proibicao' => 'proibição',
        'promocao' => 'promoção',
        'pronunciamento' => 'pronunciamento',
        'pronto' => 'pronto',
        'proporcao' => 'proporção',
        'proposicao' => 'proposição',
        'proposito' => 'propósito',
        'proximo' => 'próximo',
        'proxima' => 'próxima',
        'publica' => 'pública',
        'publicacao' => 'publicação',
        'publicacoes' => 'publicações',
        'publico' => 'público',
        'punicao' => 'punição',
        'qualificacao' => 'qualificação',
        'razao' => 'razão',
        'razoavel' => 'razoável',
        'rea' => 'ré',
        'realizacao' => 'realização',
        'reapreciacao' => 'reapreciação',
        'recebido' => 'recebido',
        'recepcao' => 'recepção',
        'reconsideracao' => 'reconsideração',
        'reconvencao' => 'reconvenção',
        'redacao' => 'redação',
        'reducao' => 'redução',
        'reflexao' => 'reflexão',
        'regulamentacao' => 'regulamentação',
        'reincidencia' => 'reincidência',
        'reiteracao' => 'reiteração',
        'relevancia' => 'relevância',
        'remissao' => 'remissão',
        'reparacao' => 'reparação',
        'replica' => 'réplica',
        'reposicao' => 'reposição',
        'represa' => 'represa',
        'representacao' => 'representação',
        'requisicao' => 'requisição',
        'rescisao' => 'rescisão',
        'resolucao' => 'resolução',
        'restituicao' => 'restituição',
        'retencao' => 'retenção',
        'retificacao' => 'retificação',
        'reu' => 'réu',
        'revisao' => 'revisão',
        'revogacao' => 'revogação',
        'sansao' => 'sansão',
        'sancao' => 'sanção',
        'sancoes' => 'sanções',
        'satisfacao' => 'satisfação',
        'secao' => 'seção',
        'sentenca' => 'sentença',
        'serventia' => 'serventia',
        'sessao' => 'sessão',
        'situacao' => 'situação',
        'subsidiaria' => 'subsidiária',
        'substituicao' => 'substituição',
        'sucessao' => 'sucessão',
        'sucinto' => 'sucinto',
        'sugestao' => 'sugestão',
        'sumula' => 'súmula',
        'supressao' => 'supressão',
        'suspensao' => 'suspensão',
        'tabeliao' => 'tabelião',
        'tabelionato' => 'tabelionato',
        'taxa' => 'taxa',
        'tempo' => 'tempo',
        'tentativa' => 'tentativa',
        'terceiro' => 'terceiro',
        'titulo' => 'título',
        'titulos' => 'títulos',
        'tomada' => 'tomada',
        'traducao' => 'tradução',
        'transacao' => 'transação',
        'transcricao' => 'transcrição',
        'transferencia' => 'transferência',
        'transmissao' => 'transmissão',
        'tutela' => 'tutela',
        'uniao' => 'união',
        'unica' => 'única',
        'unico' => 'único',
        'urgencia' => 'urgência',
        'utilidade' => 'utilidade',
        'validade' => 'validade',
        'valido' => 'válido',
        'valida' => 'válida',
        'variacao' => 'variação',
        'verba' => 'verba',
        'vigencia' => 'vigência',
        'violacao' => 'violação',
        'voluntaria' => 'voluntária',
        'voluntario' => 'voluntário',
        'votacao' => 'votação',
        'votacoes' => 'votações',

        // ── Advérbios e conjunções comuns ──
        'nao' => 'não',
        'porem' => 'porém',
        'tambem' => 'também',
        'so' => 'só',  // CUIDADO: pode ser preposição inglesa, mas em texto PT-BR é "só"
        'ate' => 'até',
        'apos' => 'após',
        'atraves' => 'através',
        'alem' => 'além',
        'voce' => 'você',
        'voces' => 'vocês',
        'esta' => 'está', // CUIDADO: "esta" como pronome demonstrativo é sem acento. Risco alto, vou tirar.

        // ── Pronomes/contrações ──
        // (deixo de fora 'esta', 'estao', 'sao' por causa dos homônimos)
        'esse' => 'esse',

        // ── Numerais ordinais ──
        'primeiro' => 'primeiro',
        'segundo' => 'segundo',
        'terceiro' => 'terceiro',
        'quarto' => 'quarto',
        'quinto' => 'quinto',
        'util' => 'útil',
        'uteis' => 'úteis',
        'numero' => 'número',
        'numeros' => 'números',

        // ── Tempo / lugar ──
        'ja' => 'já',
        'la' => 'lá',
        'ca' => 'cá',
        'amanha' => 'amanhã',
        'ontem' => 'ontem',
        'manha' => 'manhã',
        'manhas' => 'manhãs',

        // ── Adjetivos comuns ──
        'breve' => 'breve',
        'classico' => 'clássico',
        'classica' => 'clássica',
        'eletronicas' => 'eletrônicas',
        'eletronicos' => 'eletrônicos',
        'familiar' => 'familiar',
        'feliz' => 'feliz',
        'historico' => 'histórico',
        'historica' => 'histórica',
        'juridico' => 'jurídico',
        'juridica' => 'jurídica',
        'logico' => 'lógico',
        'logica' => 'lógica',
        'maximo' => 'máximo',
        'maxima' => 'máxima',
        'minimo' => 'mínimo',
        'minima' => 'mínima',
        'maior' => 'maior',
        'menor' => 'menor',
        'medico' => 'médico',
        'medica' => 'médica',
        'metodico' => 'metódico',
        'metodo' => 'método',
        'patrimonio' => 'patrimônio',
        'pratico' => 'prático',
        'preferencia' => 'preferência',
        'rigido' => 'rígido',
        'sumaria' => 'sumária',
        'tecnico' => 'técnico',
        'tecnica' => 'técnica',
        'urgente' => 'urgente',
        'util' => 'útil',
        'vario' => 'vário',
        'varios' => 'vários',
        'varias' => 'várias',
        'volume' => 'volume',

        // ── Substantivos comuns ──
        'agua' => 'água',
        'aguia' => 'águia',
        'alcoolico' => 'alcoólico',
        'angulo' => 'ângulo',
        'animais' => 'animais',
        'arvore' => 'árvore',
        'avo' => 'avó',
        'avos' => 'avós',
        'bairro' => 'bairro',
        'biblioteca' => 'biblioteca',
        'cafe' => 'café',
        'cafes' => 'cafés',
        'cha' => 'chá',
        'cidade' => 'cidade',
        'codigo' => 'código',
        'codigos' => 'códigos',
        'comodo' => 'cômodo',
        'comodos' => 'cômodos',
        'consciencia' => 'consciência',
        'convencia' => 'convivência',
        'convivencia' => 'convivência',
        'corredor' => 'corredor',
        'cuidado' => 'cuidado',
        'destruicao' => 'destruição',
        'divida' => 'dívida',
        'doc.' => 'doc.',
        'epoca' => 'época',
        'escritorio' => 'escritório',
        'escritorios' => 'escritórios',
        'evidencia' => 'evidência',
        'experiencia' => 'experiência',
        'fascia' => 'fáscia',
        'familias' => 'famílias',
        'feriado' => 'feriado',
        'fenomeno' => 'fenômeno',
        'governo' => 'governo',
        'historia' => 'história',
        'historias' => 'histórias',
        'industria' => 'indústria',
        'indice' => 'índice',
        'indices' => 'índices',
        'inicio' => 'início',
        'jovem' => 'jovem',
        'lampada' => 'lâmpada',
        'lembranca' => 'lembrança',
        'lugar' => 'lugar',
        'maquina' => 'máquina',
        'medico-perito' => 'médico-perito',
        'memoria' => 'memória',
        'memorias' => 'memórias',
        'modelo' => 'modelo',
        'musica' => 'música',
        'numero' => 'número',
        'oceano' => 'oceano',
        'oculos' => 'óculos',
        'pais' => 'país', // CUIDADO: pode ser "pais" plural de pai. Risco, removo
        'palavra' => 'palavra',
        'pessima' => 'péssima',
        'pessimo' => 'péssimo',
        'porao' => 'porão',
        'preteritos' => 'pretéritos',
        'principe' => 'príncipe',
        'problema' => 'problema',
        'quilometro' => 'quilômetro',
        'recurso' => 'recurso',
        'regiao' => 'região',
        'regioes' => 'regiões',
        'remedio' => 'remédio',
        'sabado' => 'sábado',
        'sabados' => 'sábados',
        'sentido' => 'sentido',
        'sequela' => 'sequela',
        'sequencia' => 'sequência',
        'seriado' => 'seriado',
        'serie' => 'série',
        'series' => 'séries',
        'serio' => 'sério',
        'seria' => 'séria',
        'sobrescrito' => 'sobrescrito',
        'sucesso' => 'sucesso',
        'sumario' => 'sumário',
        'tato' => 'tato',
        'tomara' => 'tomara',
        'tribunal' => 'tribunal',
        'tribunais' => 'tribunais',
        'unanime' => 'unânime',
        'utilizacao' => 'utilização',
        'veiculo' => 'veículo',
        'veiculos' => 'veículos',
        'verdade' => 'verdade',
        'vermelho' => 'vermelho',
        'vespera' => 'véspera',
        'vesperas' => 'vésperas',

        // ── Nomes próprios mais comuns no judiciário (com cuidado!) ──
        'andre' => 'André',
        'antonio' => 'Antônio',
        'antonia' => 'Antônia',
        'cesar' => 'César',
        'fabio' => 'Fábio',
        'fabricio' => 'Fabrício',  // se grafia for "Fabricio"
        'felicio' => 'Felício',
        'gabriel' => 'Gabriel',
        'inacio' => 'Inácio',
        'joao' => 'João',
        'jose' => 'José',
        'julio' => 'Júlio',
        'leticia' => 'Letícia',
        'lucio' => 'Lúcio',
        'marcio' => 'Márcio',
        'mario' => 'Mário',
        'sa' => 'Sá',  // sobrenome — pode pegar "Sá" em "Ferreira & Sá"
        'sergio' => 'Sérgio',
        'tatiana' => 'Tatiana',
        'tania' => 'Tânia',
        'vinicius' => 'Vinícius',
    );

    // Remover entradas problemáticas (homônimos comuns)
    unset($dic['esta']);   // pode ser "esta" (pron.) ou "está" (verbo)
    unset($dic['pais']);   // pais (plural de pai) ou país
    unset($dic['so']);     // pode ser preposição inglesa
    unset($dic['sa']);     // pode bater em iniciais (S.A.) — substitui no contexto via regex específica
    unset($dic['serventia']); // já não-acentuado
    unset($dic['fascia']); // pode ser termo médico

    return $dic;
}

/**
 * Corrige acentos num texto. Preserva case original (Title → Título, NÃO → NÃO).
 *
 * @param string $texto
 * @return string
 */
function corrigir_acentos_juridico($texto) {
    if (!is_string($texto) || $texto === '') return $texto;
    $dic = _dic_acentos_juridico();
    // Word boundary com lookahead/lookbehind tolerantes a maiúsculas/acentos.
    // Pattern: \b(palavra)\b case-insensitive (Unicode).
    foreach ($dic as $k => $v) {
        if (mb_strpos(mb_strtolower($texto), $k) === false) continue; // skip rápido
        $pattern = '/\b' . preg_quote($k, '/') . '\b/iu';
        $texto = preg_replace_callback($pattern, function($m) use ($v) {
            $orig = $m[0];
            // Preserva case:
            //  - tudo MAIÚSCULO: retorna MAIÚSCULO
            //  - primeira maiúscula: retorna Capitalizada
            //  - resto: minúsculo
            if ($orig === mb_strtoupper($orig)) return mb_strtoupper($v);
            $firstChar = mb_substr($orig, 0, 1);
            if ($firstChar === mb_strtoupper($firstChar) && $firstChar !== mb_strtolower($firstChar)) {
                return mb_strtoupper(mb_substr($v, 0, 1)) . mb_substr($v, 1);
            }
            return $v;
        }, $texto);
    }
    return $texto;
}

} // if function_exists
